version: '3.9'
services:
  # PostgreSQL database
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgis/postgis:${POSTGRES_VERSION}
    restart: always
    ports:
      - "3432:5432"
    networks:
      - ${NETWORK}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}

networks:
  ariesview:
    name: ${NETWORK}
    driver: bridge